python -m torch.distributed.launch --nproc_per_node 1 --master_port 29515 main_prompt_adafactor.py \
	--cuda 4 \
	--lr 5e-1 \
	--weight_decay 1e-5 \
	--max_grad_norm 1.0 \
	--batch_size_per_gpu 16 \
	--valid_size_per_gpu 32 \
	--test_size_per_gpu 32 \
	--gradient_accumulation_steps 2 \
	--max_epoch 80 \
	--num_workers 4 \
	--save_step 100000 \
	--eval_step 100000 \
	--save_dir t5ner_ckpt \
	--seed 42 \
	--model T5NER \
	--model_name google/t5-v1_1-base \
	--train_file_name data_conll/newtrain_onlyent.txt \
	--valid_file_name data_conll/newvalid_onlyent.txt \
	--test_file_name data_conll/newtest_onlyent.txt \
	--train_sample \
	--max_length 128 \
	--adam_epsilon 1e-8 \
	--warmup_steps 0.1 \
	--load_ckpt 0 \
	--use_lm_adapted 1 \
	--lm_adapted_path  /data/qin/lm_adapted_t5model/torch_ckpt/base/pytorch_model.bin \
	--prompt_number 200 \
	--ifckpt_onlymodel 1 \


